global:
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']
      # - job_name: 'zookeeper'
      #   static_configs:
      #     -targets:
      #       -.....:2181
